# messages: &messages
  # forbidden: 'You are not allowed to perform this action.'
  # unauthorized: 'You must authenticate first.'

development: &common
  courier:
    enabled:  true
    from:     'noreply@pagehub.org'

production:
  <<: *common
  # <<: *messages

test:
  courier:
    enabled: false
  # <<: *messages